### ISSUE TITLE
Freezing MEGA sw causes bad thumbnails

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-release-prep#1]
I will refer to new software, making full use of the MEGA65 capabilities as "MEGA sw" from now on: Titles to be tested are on MEGAGAME.D81 for example. Freezing those will result in garbled thumbnails inside freezer.

**Comment by gardners** [comment]
Please test with the head of hwsc, as I am not aware of any circumstance in which it doesn't generate valid thumbnails.  [REDACTED], for example, gets a valid thumbnail now.
