### ISSUE TITLE
Demo disk #1: Menu displays "ROM 920287 - PAL MODE"

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-release-prep#9]
The demo disk menu's title screen displays the message "ROM 920287 - PAL MODE." This information is hard-coded on line 420 and doesn't seem to read these values from anywhere. I'm running ROM 920376 (RC 0.95) in NTSC mode. The message should probably just be removed.

**Comment by gurcei** [comment]
Aah, at the time, it was intended to mean "tested with rom version xxx". Think I suggested something more verbose like that to deft, but he felt the extra text would make the title screen look a bit ugly. (I was thinking of adding the core version it was tested against too).

As for what's the best way forward, not sure, happy to consider alternatives.

**Comment by deftmega** [comment]
I will look into it and probably just remove the line soon

**Comment by deftmega** [comment]
fixed and commited
